name: Workflow Commands

on:
  - push

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::This is an error message"

      - name: Setting an error message with params
        run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::This is an error message"
      
      - name: Setting an debug message with params
        run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::This is an debug message"
      
      - name: Setting an warning message with params
        run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::This is an warning message"

      - name: Setting an notice message with params
        run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::This is an notice message"

      - name: Grouping logs
        run: |
          echo "::group::Some logs"
          echo "Inside the group"
          echo "Inside the group"
          echo "::endgroup::"
      
      - name: Masking a value
        run: echo "::add-mask::secret"

      - name: Echo a value
        run: echo "secret"