name: Working Dirs & Shells

on:
  - push

defaults:
  run:
    shell: bash
    # working-directory: ./subdir

jobs:
  display-wd-info-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: Change Working Directory
        working-directory: /home/runner
        run: pwd

  display-wd-info-windows:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE

      - name: Python Shell
        shell: python
        run: |
          import os
          print(os.getcwd())
          print(os.listdir())
          print(os.environ['GITHUB_SHA'])
          print(os.environ['GITHUB_REPOSITORY'])
          print(os.environ['GITHUB_WORKSPACE'])
